# Generated by Django 4.1.2 on 2022-10-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeparateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, default='No Description', null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('guests', models.IntegerField(blank=True, default=0, null=True)),
                ('ical_link', models.URLField(blank=True, default='', null=True)),
                ('url', models.SlugField(blank=True, default='', null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='listings.amenities')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='No Description', null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('guests', models.IntegerField(blank=True, default=1, null=True)),
                ('ical_link', models.URLField(blank=True, default='', null=True)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('check_in', models.TimeField(blank=True, default='14:00:00', null=True)),
                ('check_out', models.TimeField(blank=True, default='10:00:00', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, default=-34.36395675807039, null=True)),
                ('longitude', models.FloatField(blank=True, default=21.43102905736344, null=True)),
                ('url', models.SlugField(blank=True, default='', null=True)),
                ('instant_booking', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.FloatField(default=0)),
                ('is_price_per_unit', models.BooleanField(blank=True, default=False, null=True)),
                ('cleaning_fee', models.FloatField(blank=True, default=0, null=True)),
                ('security_deposit', models.FloatField(blank=True, default=0, null=True)),
                ('video', models.URLField(blank=True, default='', null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='listings.amenities')),
                ('city', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='listings.city')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.gallery')),
                ('listing_type', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='listings.listingtype')),
                ('province', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='listings.province')),
                ('room_type', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='listings.roomtype')),
                ('separate_rooms', models.ManyToManyField(blank=True, to='listings.separateroom')),
            ],
        ),
    ]
