# Generated by Django 4.1.2 on 2022-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(to='listings.amenities'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='separateroom',
            name='amenities',
            field=models.ManyToManyField(to='listings.amenities'),
        ),
        migrations.RemoveField(
            model_name='separateroom',
            name='gallery',
        ),
        migrations.AddField(
            model_name='listing',
            name='booked_dates',
            field=models.ManyToManyField(to='listings.bookeddates'),
        ),
        migrations.AddField(
            model_name='separateroom',
            name='booked_dates',
            field=models.ManyToManyField(to='listings.bookeddates'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gallery',
            field=models.ManyToManyField(to='listings.gallery'),
        ),
        migrations.AddField(
            model_name='separateroom',
            name='gallery',
            field=models.ManyToManyField(to='listings.gallery'),
        ),
    ]
