# Generated by Django 4.1.2 on 2022-10-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_bookeddates_alter_listing_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separateroom',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='separateroom',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='separateroom',
            name='guests',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
