# Generated by Django 4.1.3 on 2022-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeddates',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookeddates',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
