# Generated by Django 4.1.3 on 2022-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_bookeddates_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='booked_dates',
            field=models.ManyToManyField(blank=True, to='listings.bookeddates'),
        ),
        migrations.AlterField(
            model_name='separateroom',
            name='booked_dates',
            field=models.ManyToManyField(blank=True, to='listings.bookeddates'),
        ),
    ]
