# Generated by Django 4.1.3 on 2023-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_booked_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
